"""
ClassNotes AI — HuggingFace Space entry point.

Upload a classroom board photo and receive structured study notes
generated by Qwen2-VL-2B-Instruct.
"""

import os
from functools import lru_cache

import gradio as gr
import torch
from PIL import Image
from transformers import AutoProcessor, Qwen2VLForConditionalGeneration

# --------------------------------------------------------------------------- #
# Model                                                                        #
# --------------------------------------------------------------------------- #

MODEL_NAME = os.getenv("BOARD_NOTES_MODEL", "Qwen/Qwen2-VL-2B-Instruct")
TEST_MAX_IMAGE_SIDE = int(os.getenv("TEST_MAX_IMAGE_SIDE", "1024"))

PROMPT = """Analyze the classroom board image carefully.

Generate structured classroom notes using the following format:

Topic:
Concepts:
Explanation:
Examples:
Practice Questions:

Ensure:
- clear headings
- bullet points
- simplified explanations for students
- include formulas if present"""


@lru_cache(maxsize=1)
def load_model():
    torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32
    model = Qwen2VLForConditionalGeneration.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch_dtype,
        device_map="auto",
    )
    processor = AutoProcessor.from_pretrained(MODEL_NAME)
    return model, processor


# --------------------------------------------------------------------------- #
# Inference                                                                    #
# --------------------------------------------------------------------------- #

def prepare_image_for_inference(image: Image.Image, max_side: int) -> Image.Image:
    width, height = image.size
    largest_side = max(width, height)
    if largest_side <= max_side:
        return image

    scale = max_side / float(largest_side)
    new_size = (max(1, int(width * scale)), max(1, int(height * scale)))
    return image.resize(new_size, Image.Resampling.LANCZOS)


def generate_notes(image: Image.Image, quick_test_mode: bool) -> str:
    if image is None:
        return "Please upload a board image first."

    image = prepare_image_for_inference(image, TEST_MAX_IMAGE_SIDE)

    try:
        model, processor = load_model()
    except Exception as exc:
        return f"Model failed to load: {exc}"

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": image},
                {"type": "text", "text": PROMPT},
            ],
        }
    ]

    text = processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = processor(
        text=[text],
        images=[image],
        padding=True,
        return_tensors="pt",
    ).to(model.device)

    max_new_tokens = 220 if quick_test_mode else 800

    with torch.inference_mode():
        output_ids = model.generate(**inputs, max_new_tokens=max_new_tokens)

    # Return only newly generated tokens (strip the prompt)
    input_len = inputs["input_ids"].shape[1]
    generated_ids = output_ids[0][input_len:]
    return processor.decode(generated_ids, skip_special_tokens=True)


# --------------------------------------------------------------------------- #
# Gradio UI                                                                    #
# --------------------------------------------------------------------------- #

with gr.Blocks(title="ClassNotes AI", theme=gr.themes.Soft()) as demo:
    gr.Markdown(
        """
        # 📝 ClassNotes AI
        Upload a photo of a classroom whiteboard or blackboard and get
        **structured study notes** powered by Qwen2-VL.
        """
    )

    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(
                type="pil",
                label="Board Image",
                sources=["upload", "webcam", "clipboard"],
            )
            quick_test_mode = gr.Checkbox(
                value=True,
                label="Quick test mode (faster, shorter output)",
            )
            submit_btn = gr.Button("Generate Notes", variant="primary")

        with gr.Column(scale=1):
            notes_output = gr.Textbox(
                label="Generated Notes",
                lines=28,
                show_copy_button=True,
                placeholder="Your structured notes will appear here…",
            )

    submit_btn.click(
        fn=generate_notes,
        inputs=[image_input, quick_test_mode],
        outputs=notes_output,
    )

if __name__ == "__main__":
    demo.launch()
